### ISSUE TITLE
AJ's Prelim Report

### ISSUE THREAD

**Issue by ajaparicio36** [Dreamsoft-CPU/RawMats#1]
### Name
Anthony John Aparicio
### Role
Scrum Master

### General
- Created [Google Drive](https://drive.google.com/drive/folders/1gvzAOT_P8MKs4iXoNSvRQmNOl6cNC5te?usp=sharing) folders for storing collection of documents
- Did Minutes of the Meetings for Prelims period meetings
- Created the GitHub organization, repository for the official project, and GitHub Projects for RawMats.
- Created ClickUp for our Project Management Board
### [Vision and Scope Document](https://docs.google.com/document/d/15C6-p-WfCcFjSlp11TwCkEAC6w4_dcYo/edit)
- Built the format of the document (excluding headers and footers)
- Wrote majority of the statements of the chapters
- Wrote the features, extracted from client meetings
- Wrote some of the risks and rated them
- Wrote some of the assumptions
- Wrote users through collaboration of the team members
- Wrote the problem statement and expanded the project background
### [Software Architecture Document](https://docs.google.com/document/d/1gmZSYennKLNFZvql-9D0PhQZ7KEgwsTf/edit)
- Started on the Software Architecture format (excluding headers and footers)
- Expanded work of other teammates from section 1 and put them on the final document
- Wrote functional requirements
- Wrote majority of section 2
- Sketched a rough draft of context diagrams for section 3

**Comment by chdean-09** [comment]
Great work, AJ! I can confirm and agree with your contributions!
